### ISSUE TITLE
[Readme] Known Issues Summary / TODO List

### ISSUE THREAD

**Issue by BloCamLimb** [BloCamLimb/ModernUI#6]
### Font Renderer
- [x] Blurring with other render type builder (Fixed since 1.5.5.52)
- [x] Chars not display / layout properly (extremely confused) while game is paused (Since 1.14+) (Fixed since 1.5.6.53)
- [x] Chars are drawn blank or get dislocated (combined with other chars) when a new texture mapping started (Since 1.14+) (Fixed since 1.5.6.53)
- [x] Not support mipmap, causing font blurred when being scaled (Supported since 1.5.5.52)
- [x] Not support unicode supplementary multilingual plane (1.16+)
- [ ] Bug: depth test & transparency order in world rendering (suspended by mojang, 1.15+)
### TODO (1.16+)
- [ ] New and very complicated mouse/drag/key event system
- [ ] New view state system and listeners
- [ ] Remove all `GL_QUADS`, it's deprecated, use `drawElements(GL_TRIANGLES)`
- [ ] Use z-order, use VBO(GL1.5) VAO(GL3.0) SSBO(GL4.3).
- [ ] Data-driven system, visual editor in game

**Comment by BloCamLimb** [comment]
This page has been deprecated. No more updates.
